# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6bad4b6effe91265b63fa95aa8a2f5385741d3d1f360034f9293114de2358a9b1de53c4379af86f09ab0f7617986bf54493207bff1073b3e1f6aa9e9f085452e

test:
  secret_key_base: 3424a65af389be669d5fe2a9e1ec4014982220848c79d310ef85009c1c5828b45a44409befade7444c3416697d45ca88ff1ad0421cc7a80f410ca99e838ff8cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
